create table if not exists public.users (
  id bigint generated by default as identity primary key,
  full_name text not null,
  email text not null unique,
  phone text not null,
  role text not null default 'customer' check (role in ('admin', 'customer')),
  password_hash text not null,
  password_salt text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.sessions (
  token text primary key,
  user_id bigint not null references public.users(id) on delete cascade,
  expires_at bigint not null
);

alter table public.users enable row level security;
alter table public.sessions enable row level security;
